const INCLUDE_KEYWORDS = [
  'software engineer',
  'software developer',
  'sde',
  'backend engineer',
  'frontend engineer',
  'front end engineer',
  'front-end engineer',
  'back end engineer',
  'back-end engineer',
  'full stack',
  'fullstack',
  'full-stack',
  'platform engineer',
  'infrastructure engineer',
  'systems engineer',
  'site reliability',
  'devops engineer',
  'data engineer',
  'ml engineer',
  'machine learning engineer',
  'cloud engineer',
  'mobile engineer',
  'ios engineer',
  'android engineer',
  'engineer ii',
  'engineer 2',
  'engineer iii',
  'senior engineer',
  'staff engineer',
];

const EXCLUDE_KEYWORDS = [
  'product manager',
  'program manager',
  'engineering manager',
  'director',
  'vice president',
  ' vp ',
  'recruiter',
  'designer',
  'ux ',
  'ui/ux',
  'data scientist',
  'data analyst',
  'business analyst',
  'sales',
  'marketing',
  'finance',
  'legal',
  'counsel',
  'accountant',
  'hr ',
  'human resources',
  'support engineer',
  'solutions engineer',
  'customer success',
  'intern',
  'internship',
];

export function isSdeRole(title: string): boolean {
  const lower = title.toLowerCase();
  if (EXCLUDE_KEYWORDS.some(kw => lower.includes(kw))) return false;
  return INCLUDE_KEYWORDS.some(kw => lower.includes(kw));
}
